/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionSaveRouteImport } from './routes/extension/save'
import { Route as AppTagsRouteImport } from './routes/app/tags'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppFavoritesRouteImport } from './routes/app/favorites'
import { Route as AppArticlesRouteImport } from './routes/app/articles'
import { Route as AppArchiveRouteImport } from './routes/app/archive'
import { Route as ApiV1ArticlesRouteImport } from './routes/api/v1/articles'
import { Route as ApiExtensionArticlesRouteImport } from './routes/api/extension/articles'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionSaveRoute = ExtensionSaveRouteImport.update({
  id: '/extension/save',
  path: '/extension/save',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesRoute = AppArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AppRoute,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1ArticlesRoute = ApiV1ArticlesRouteImport.update({
  id: '/api/v1/articles',
  path: '/api/v1/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionArticlesRoute = ApiExtensionArticlesRouteImport.update({
  id: '/api/extension/articles',
  path: '/api/extension/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/articles': typeof AppArticlesRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/home': typeof AppHomeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tags': typeof AppTagsRoute
  '/extension/save': typeof ExtensionSaveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/extension/articles': typeof ApiExtensionArticlesRoute
  '/api/v1/articles': typeof ApiV1ArticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/articles': typeof AppArticlesRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/home': typeof AppHomeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tags': typeof AppTagsRoute
  '/extension/save': typeof ExtensionSaveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/extension/articles': typeof ApiExtensionArticlesRoute
  '/api/v1/articles': typeof ApiV1ArticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/articles': typeof AppArticlesRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/home': typeof AppHomeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tags': typeof AppTagsRoute
  '/extension/save': typeof ExtensionSaveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/extension/articles': typeof ApiExtensionArticlesRoute
  '/api/v1/articles': typeof ApiV1ArticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-docs'
    | '/app'
    | '/login'
    | '/privacy'
    | '/app/archive'
    | '/app/articles'
    | '/app/favorites'
    | '/app/home'
    | '/app/settings'
    | '/app/tags'
    | '/extension/save'
    | '/api/auth/$'
    | '/api/extension/articles'
    | '/api/v1/articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-docs'
    | '/app'
    | '/login'
    | '/privacy'
    | '/app/archive'
    | '/app/articles'
    | '/app/favorites'
    | '/app/home'
    | '/app/settings'
    | '/app/tags'
    | '/extension/save'
    | '/api/auth/$'
    | '/api/extension/articles'
    | '/api/v1/articles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-docs'
    | '/app'
    | '/login'
    | '/privacy'
    | '/app/archive'
    | '/app/articles'
    | '/app/favorites'
    | '/app/home'
    | '/app/settings'
    | '/app/tags'
    | '/extension/save'
    | '/api/auth/$'
    | '/api/extension/articles'
    | '/api/v1/articles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ExtensionSaveRoute: typeof ExtensionSaveRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiExtensionArticlesRoute: typeof ApiExtensionArticlesRoute
  ApiV1ArticlesRoute: typeof ApiV1ArticlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension/save': {
      id: '/extension/save'
      path: '/extension/save'
      fullPath: '/extension/save'
      preLoaderRoute: typeof ExtensionSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tags': {
      id: '/app/tags'
      path: '/tags'
      fullPath: '/app/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/articles': {
      id: '/app/articles'
      path: '/articles'
      fullPath: '/app/articles'
      preLoaderRoute: typeof AppArticlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/archive': {
      id: '/app/archive'
      path: '/archive'
      fullPath: '/app/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/articles': {
      id: '/api/v1/articles'
      path: '/api/v1/articles'
      fullPath: '/api/v1/articles'
      preLoaderRoute: typeof ApiV1ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/articles': {
      id: '/api/extension/articles'
      path: '/api/extension/articles'
      fullPath: '/api/extension/articles'
      preLoaderRoute: typeof ApiExtensionArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppArchiveRoute: typeof AppArchiveRoute
  AppArticlesRoute: typeof AppArticlesRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppHomeRoute: typeof AppHomeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTagsRoute: typeof AppTagsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchiveRoute: AppArchiveRoute,
  AppArticlesRoute: AppArticlesRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppHomeRoute: AppHomeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTagsRoute: AppTagsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiDocsRoute: ApiDocsRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ExtensionSaveRoute: ExtensionSaveRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiExtensionArticlesRoute: ApiExtensionArticlesRoute,
  ApiV1ArticlesRoute: ApiV1ArticlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
